var tm_cannabis = [
   {
     id: 1,
     name: "White Skunk",
     image: 'cannabis/white_skunk.jpg',
     enabled: true,
     nivel: 1,
     quantity: 1,
     delay: 1000,
     sell_cost: 1.00,
     value_cost: 50.00,
     manager_cost: 500.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 2.4,
     percentage_cost: 4.6
   },
  {
     id: 2,
     name: "Purple Bud",
     image: 'cannabis/purple_bud.jpg',
     enabled: false,
     nivel: 2,
     quantity: 0,
     delay: 3000,
     sell_cost: 2.70,
     value_cost: 92.00,
     manager_cost: 1200.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 3.2,
     percentage_cost: 5.6
   },
   {
     id: 3,
     name: "Sensi Skunk",
     image: 'cannabis/sensi_skunk.jpg',
     enabled: false,
     nivel: 3,
     quantity: 0,
     delay: 5000,
     sell_cost: 4.20,
     value_cost: 700.00,
     manager_cost: 7000.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 4.3,
     percentage_cost: 7.0
   },
  {
     id: 4,
     name: "Hindu Kush",
     image: 'cannabis/hindu_kush.jpg',
     enabled: false,
     nivel: 4,
     quantity: 0,
     delay: 7000,
     sell_cost: 6.00,
     value_cost: 6100.00,
     manager_cost: 41000.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 5.5,
     percentage_cost: 9.3
   },
  {
     id: 5,
     name: "Purple Bud Automatic",
     image: 'cannabis/purple_bud_automatic.jpg',
     enabled: false,
     nivel: 5,
     quantity: 0,
     delay: 10000,
     sell_cost: 11.00,
     value_cost: 30000.00,
     manager_cost: 120500.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 6.4,
     percentage_cost: 11.3
   },
   {
     id: 6,
     name: "White Skunk Automatic",
     image: 'cannabis/white_skunk_automatic.jpg',
     enabled: false,
     nivel: 6,
     quantity: 0,
     delay: 15000,
     sell_cost: 14.30,
     value_cost: 120000.00,
     manager_cost: 1000000.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 7.2,
     percentage_cost: 13.3
   },
   {
     id: 7,
     name: "Skunk #1",
     image: 'cannabis/skunk_1.jpg',
     enabled: false,
     nivel: 7,
     quantity: 0,
     delay: 20000,
     sell_cost: 17.10,
     value_cost: 650000.00,
     manager_cost: 6000000.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 8.1,
     percentage_cost: 15.7
   },
   {
     id: 8,
     name: "Sativa Mexicana",
     image: 'cannabis/sativa_mexicana.jpg',
     enabled: false,
     nivel: 8,
     quantity: 0,
     delay: 30000,
     sell_cost: 23.40,
     value_cost: 1250000.00,
     manager_cost: 24000000.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 9.8,
     percentage_cost: 17.1
   },
   {
     id: 9,
     name: "Master Kush",
     image: 'cannabis/master_kush.png',
     enabled: false,
     nivel: 9,
     quantity: 0,
     delay: 60000,
     sell_cost: 32.40,
     value_cost: 80000000.00,
     manager_cost: 600000000.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 10.3,
     percentage_cost: 19.2
   },
   {
     id: 10,
     name: "White Widow",
     image: 'cannabis/white_widow.png',
     enabled: false,
     nivel: 10,
     quantity: 0,
     delay: 120000,
     sell_cost: 100.40,
     value_cost: 340000000.00,
     manager_cost: 1000000000.00,
     manager_bought: false,
     manager_task_active: false,
     percentage_gain: 11.7,
     percentage_cost: 21.1
   }
];